name: Custom integration test

on:
  push:
    branches:
      - main
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run integration testing script as root
        working-directory: ${{ github.workspace }}
        run: |
          sudo chmod +x ./pndp_test.sh
          sudo ./pndp_test.sh proxy
          sudo ./pndp_test.sh responder
        continue-on-error: false